### ISSUE TITLE
what is the best flavor of ice cream

### ISSUE THREAD

**Issue by Mr-Darfler** [fcs-cs/cs2-student-files#10]

**Comment by Mr-Darfler** [comment]
Strawberry is totally the best

**Comment by BLehrer99** [comment]
@Mr-Darfler No way! Cookie dough is soooooo good.

**Comment by Mr-Darfler** [comment]
@BLehrer99 do they make any flavor other than chocolate chip cookie dough? What about oatmeal rasin?

**Comment by gordoniii** [comment]
cookies and cream

**Comment by pryan4** [comment]
vanilla ftw

**Comment by BLehrer99** [comment]
![](https://i.imgur.com/FKM0Vfl.gif?noredirect)

**Comment by awualex** [comment]
np Strawberry is best

**Comment by Mr-Darfler** [comment]
Looks like we've got a cookie theme going. What do we all think about making Vanilla the best flavor?

**Comment by BLehrer99** [comment]
I like that idea. Although it changes with my mood.

**Comment by Mr-Darfler** [comment]
Is cooke and cream that different from cookie dough

**Comment by BLehrer99** [comment]
Yes. Barely similar.

**Comment by gordoniii** [comment]
BIG DIFFERENCE

**Comment by Mr-Darfler** [comment]
na i agree with pat vanillas the best

**Comment by BLehrer99** [comment]
# Top Five Flavors
1) Cookies and cream
2) Cookies and cream
3) Cookies and cream
4) Cookies and cream
5) Cookies and cream

**Comment by Mr-Darfler** [comment]
# In a VERY particular order
- Vanilla
- Cookie Dough
- Strawberry
- Cookies and Cream

can I get a +1 @fcs-cs/cs2-2019

**Comment by awualex** [comment]
1. strawberry
2. mint
3. green cookies and cream
4. vanilla
5. cookie dough

**Comment by BLehrer99** [comment]
# Red Bean FTW

**Comment by Mr-Darfler** [comment]
I like green tea, but you dropped @gordoniii 's suggestion

**Comment by Mr-Darfler** [comment]
Good conversation, I'm a branch and PR.

**Comment by pryan4** [comment]
huh i can still go
