### ISSUE TITLE
Classroom Norms and Expectations

### ISSUE THREAD

**Issue by Mr-Darfler** [fcs-cs/cs2-student-files#12]
# Notes from 2/6

### Definitions

Norms
- Standard, agreed upon
- Both Implicit and explicit

Normative
- What's perceived as normal
- e.g. heterosexuality

Normal
- Abiding the norms

### Why do we have norms
- Makes you feel safe and secure
- The essence of social order
- Understanding of expectations

**Comment by Mr-Darfler** [comment]
Answer the following:

## Learning
- I **learn** best when: 
- So I want a classroom that is: 
- In order to achieve this, I propose the following classroom norm: 

## Contributing
- I **contribute** best when: 
- So I want a classroom that: 
- In order to achieve this, I propose the following classroom norm: 

## Expectations

(Please add only one for each expectation)
- I expect my teacher to:
- I expect my classmates to:
- I expect myself to:

**Comment by pryan4** [comment]
## Learning
* I **learn** best when: we actually take what we learn in class and incorporate it into our own code.
* I want a classroom that is: constantly learning and developing at a shared pace.
*  In order to achieve this I propose the following classroom norm: to always ask questions and to speak up when you do not understand a concept or activity.

**Comment by BLehrer99** [comment]
## Learning
* I **learn** best when: I can work through a problem myself
* So I want a classroom that is: project and trial and error oriented
* In order to achieve this, I propose the following classroom norm: allow others to solve problems for themselves

**Comment by gordoniii** [comment]
I learn best when: The class is engaging and making me want to learn.
So I want a classroom that is: Engaging and fun but at the same time helpful.
In order to achieve this, I propose the following classroom norm: That before we move on to another topic or section of the lesson that we make sure that everybody understand what we did first.

**Comment by Jkohl1** [comment]
## Learning
* I **learn** best when: I have a goal to work towards
* So I want a classroom that is: emphasizes goals
* In order to achieve this, I propose the following classroom norm: Have clear goals before we start things

**Comment by pryan4** [comment]
## Contributing
* I contribute best when I fully understand the concept presented and have a challenging but manageable task at hand.
* So I want a classroom that is fully engaged and that focuses alot on the individual rather than the group as a whole.
* Classroom norm: To come to class fully prepared and while in class be fully engaged in the activities given.

**Comment by BLehrer99** [comment]
## Contributing
* I **contribute** best when: I can contribute freely, even if my contribution is incorrect or incomplete
* So I want a classroom that: open and non-judgmental
* In order to achieve this, I propose the following classroom norm: be open to other's thoughts and ideas

**Comment by Jkohl1** [comment]
## Contributing
* I **contribute** best when: I feel comfortable with what we are talking about
* So I want a classroom that: Helps me learn what I need to learn
* In order to achieve this, I propose the following classroom norm: Don't let others fall behind

**Comment by pryan4** [comment]
## Expectations
* I expect my teacher to: pay attention to the pace of everyone in the learning process and help everyone be on the same page.
* I expect my classmates to be engaged in the learning process and to help each other.
* I expect myself to come prepared everyday and to be respectful to the space, people, and equipment.

**Comment by gordoniii** [comment]
I contribute best when: I feel that I can bring my knowledge of a situation to the discussion 
So I want a classroom that: Is able to have open discussion and that we can help each other with problems.
In order to achieve this, I propose the following classroom norm be that we ask questions when needed.

**Comment by gordoniii** [comment]
I expect my teacher to: Teach me to the best of their ability.
I expect my classmates to: Hold me accountable for my mistakes.
I expect myself to: Do the best I can.

**Comment by Jkohl1** [comment]
## Expectations

* I expect my teacher to: Move at a speed where we can really understand ideas
* I expect my classmates to: Collaborate well
* I expect myself to: Keep up with what we are doing

**Comment by BLehrer99** [comment]
## Expectations

* I expect my teacher to: seek student input in solving a problem
* I expect my classmates to: be engaged during class
* I expect myself to: be open to other's ideas

**Comment by Mr-Darfler** [comment]
@BLehrer99 

> ## Expectations
> * I expect my teacher to: seek student input in solving a problem
> * I expect my classmates to: be engaged during class
> * I expect myself to: be open to other's ideas

I really appreciate your expectation of me as a teacher. I think this would be a good one for the whole class.

**Comment by pryan4** [comment]
@BLehrer99 "I expect my classmates to: be engaged during class." 

I think we need some more specificity here.

**Comment by pryan4** [comment]
@Jkohl1 "Helps me learn what I need to learn"

Can we maybe word this a different way? It sounds repetitive.

**Comment by pryan4** [comment]
@Jkohl1 *" I **contribute** best when: I can contribute freely, even if my contribution is incorrect or incomplete"

I feel that relates to my norm "* I contribute best when I fully understand the concept presented and have a challenging but manageable task at hand."

**Comment by pryan4** [comment]
@gordoniii "That before we move on to another topic or section of the lesson that we make sure that everybody understand what we did first."

I  think that conflicts with @BLehrer99's norm of "* allow others to solve problems for themselves"

**Comment by pryan4** [comment]
@Jkohl1 * "I **contribute** best when: I feel comfortable with what we are talking about"

I think this needs to discuss this one, or reword it

**Comment by pryan4** [comment]
@BLehrer99 * "I expect my classmates to be engaged during class"

This relates to @Jkohl1's norm "Collaborate well."

**Comment by BLehrer99** [comment]
@pryan4 

> ## Expectations
> * I expect my teacher to: pay attention to the pace of everyone in the learning process and help everyone be on the same page.
> * I expect my classmates to be engaged in the learning process and to help each other.
> * I expect myself to come prepared everyday and to be respectful to the space, people, and equipment.

- I think your expectation for the teacher is very similar to mine as they build off each other. A good way to help maintain a good pace for everyone is to seek everyone's input.
- Additionally, your last expectation is critical and similar to mine. A good way to be respectful to others is by accepting their input and ideas.

**Comment by BLehrer99** [comment]
@Jkohl1

> ## Learning
> * I **learn** best when: I have a goal to work towards
> * So I want a classroom that is: emphasizes goals
> * In order to achieve this, I propose the following classroom norm: Have clear goals before we start things

- Your norm about learning best when you have a goal to work toward is important to me too. Would having a project based work environment aid in this?
- Regarding your final norm, I think this exercise is a good way to create those clear goals before we begin our course.

**Comment by BLehrer99** [comment]
@gordoniii 

> I contribute best when: I feel that I can bring my knowledge of a situation to the discussion
> So I want a classroom that: Is able to have open discussion and that we can help each other with problems.
> In order to achieve this, I propose the following classroom norm be that we ask questions when needed.

- Your norms about needing to bring your own knowledge to a discussion connects well to @pryan4 's expectation for people to come to class prepared.
- Asking questions is critical and I really like this norm. It is a great way to effectively learn!

**Comment by Jkohl1** [comment]
@pryan4 > * pay attention to the pace of everyone in the learning process and help everyone be on the same page.

This is similar to my expectations from the teacher in that we both want to maintain a good pace.

**Comment by Jkohl1** [comment]
@BLehrer99 * I expect my classmates to: be engaged during class

This comment is similar to @pryan4 * I expect my classmates to be engaged in the learning process and to help each other. 

Both expect their classmates to be engaged in their learning

**Comment by Jkohl1** [comment]
@BLehrer99 * In order to achieve this, I propose the following classroom norm: allow others to solve problems for themselves

I think that this is good, but at a certain point, we should help people if they are stuck.

**Comment by Jkohl1** [comment]
* In order to achieve this, I propose the following classroom norm: Have clear goals before we start things

**Comment by Jkohl1** [comment]
* In order to achieve this, I propose the following classroom norm: Don't let others fall behind

**Comment by BLehrer99** [comment]
- Allow others to solve problems for themselves
- Be open to other's thoughts and ideas

**Comment by pryan4** [comment]
## Norms
* to always ask questions and to speak up when you do not understand a concept or activity.
* To come to class fully prepared and while in class be fully engaged in the activities given.

**Comment by gordoniii** [comment]
- To make sure you understand the material. And if not, to ask questions. 

- Keep a open mind to all ideas and other ways of solving problems.

**Comment by awualex** [comment]
Learning:
* I learn best when I have a specific, measurable, attainable, relevant, and timely goal during studying, and I could always obtain immediae feedback after every try to accheive a deliberate practice.
* So I want a classroom that is responsive, practical, project, and error-feedback oriented.
* In order to achieve this, I propose the following classroom norm: **Have clear goals and keen/not fear to point out errors in urs and others**

**Comment by Mr-Darfler** [comment]
closed by #13
